---
server:
  port: 8080
  contextPath: /LycaMediaApiServer
---
spring:
  profiles: lyca
datasource:
  sampleapp:
    url: jdbc:mysql://localhost:3306/lvc
    username: root
    password: Lyca123!
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQL5Dialect
---
spring:
  profiles: dev,default
datasource:
  sampleapp:
    url: jdbc:mysql://81.24.198.45:3306/lvc
    username: root
    password: Lyca123!
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQL5Dialect

